# Generated by Django 5.1.3 on 2024-12-19 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('restored_at', models.DateTimeField(blank=True, null=True)),
                ('transaction_id', models.UUIDField(blank=True, null=True)),
                ('created_by', models.IntegerField(null=True)),
                ('updated_by', models.IntegerField(null=True)),
                ('deleted_by', models.IntegerField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('room_no', models.IntegerField(blank=True, null=True)),
                ('price', models.CharField(blank=True, max_length=255, null=True)),
                ('sequence', models.IntegerField(blank=True, null=True)),
                ('status', models.BooleanField(blank=True, default=True, null=True)),
            ],
            options={
                'db_table': 'room',
            },
        ),
    ]
