# Generated by Django 5.1.3 on 2024-12-23 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0002_checkin'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkin',
            name='discount',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
